# https://etcd.io/docs/v3.5/install/#install-pre-built-binaries
# https://github.com/etcd-io/etcd/releases/tag/v3.5.21
# https://console.cloud.google.com/artifacts/docker/etcd-development/us/gcr.io/etcd

FROM gcr.io/etcd-development/etcd:v3.6.9

COPY ./etcd /etc/default/etcd
